### ISSUE TITLE
保存的html文件部分中文乱码，部分图片无法加载

### ISSUE THREAD

**Issue by Kegekkk** [Mr-Gump/iCourse_so_easy#4]
作者大大辛苦了，刚才测试了两个课程，其中一个正常，但另一个出现问题
出现问题的课程：
![chrome_wmotkloGu6](https://user-images.githubusercontent.com/57929335/79811860-bbb2f280-83a9-11ea-9be1-f90f8e753625.png)
![chrome_sSOWuKFhJJ](https://user-images.githubusercontent.com/57929335/79811863-bd7cb600-83a9-11ea-82d4-c09da068297b.png)

https://www.icourse163.org/learn/NJTU-1003701002?tid=1450218475#/learn/testlist

**Comment by Mr-Gump** [comment]
收到，我会继续修改的，感谢支持

**Comment by Mr-Gump** [comment]
非常抱歉，已经修复你所说的图片文字同时显示时乱码的问题，但是部分图片无法显示的问题暂时无法解决(网易自身图床问题),还请继续支持斧正！

**Comment by Mr-Gump** [comment]
部分图片无法显示只是极特殊情况，如需获取该答案请联系作者手动获取QQ2424659013

**Comment by Kegekkk** [comment]
非常感谢

**Comment by Kegekkk** [comment]
> 部分图片无法显示只是极特殊情况，如需获取该答案请联系作者手动获取QQ2424659013

5.0又出现了登录bug，我把4.1的那段登录代码替换过去之后就能正常登录了

**Comment by Mr-Gump** [comment]
这个是因为网易的广告推送因人而异，我会在下个版本进行修改。
